ERROR: Trying to use borrow of local but local is already dropped at this point
   NOTE: Value used here
 ---> ./test/errors/borrowcheck/return_local_borrow/main.sk:9:30
 | 9 fn someFunc(t: &Foo) -> &Foo {
 | 10     let local = Foo();
 | 11     return &local;
 | 12 }
   NOTE: Value borrowed here
 ---> ./test/errors/borrowcheck/return_local_borrow/main.sk:11:13
 | 11     return &local;
